const REPORTS_KEY = "clearanceHubReports";

/* =========================
   DOM ELEMENTS
========================= */

const reportType = document.querySelectorAll("select")[0];
const formatSelect = document.querySelectorAll("select")[1];

const reportDate = document.querySelectorAll('input[type="date"]')[0];

const generateBtn = document.querySelector(".generate-btn");

const reportsTableBody = document.getElementById(
    "reportsTableBody"
);
const hardCodedReportsHTML = reportsTableBody.innerHTML;
function goToProfile() {
    window.location.href = "Aprofile.html";
}
const warningPopup =
document.getElementById("warningPopup");

const warningOkBtn =
document.getElementById("warningOkBtn");

function showWarningPopup(message){

    warningPopup.querySelector("p").textContent =
    message;

    warningPopup.classList.add("show");
}

warningOkBtn.addEventListener("click", () => {

    warningPopup.classList.remove("show");

});
/* =========================
   MODAL ELEMENTS
========================= */

const reportModal =
document.getElementById("reportModal");

const closeReportModal =
document.getElementById("closeReportModal");

const reportDetailsContent =
document.getElementById("reportDetailsContent");

const downloadReportBtn =
document.getElementById("downloadReportBtn");


/* =========================
   STORAGE
========================= */

let reports =
JSON.parse(
localStorage.getItem(REPORTS_KEY)
);

if (!reports) {
    reports=[];
}

/* =========================
   SAVE REPORTS
========================= */

function saveReports(){

    localStorage.setItem(
        REPORTS_KEY,
        JSON.stringify(reports)
    );

}

/* =========================
   GENERATE REPORT
========================= */

function generateReport(){

    if(reportType.selectedIndex === 0){

        showWarningPopup("Please select a report type.");
        return;

    }
    const report = {

        id: Date.now(),

        name:
        reportType.value +
        " - " +
        new Date().toLocaleDateString(),

        type: reportType.value,

        reportDate: reportDate.value,

        format: formatSelect.value,

        generatedBy: "Admin Officer",

        dateGenerated:
        new Date().toLocaleDateString(),

        timeGenerated:
        new Date().toLocaleTimeString()

    };

    reports.unshift(report);

    saveReports();

    renderReports();

    alert("Report generated successfully.");

}

/* =========================
   VIEW REPORT
========================= */

let currentReport = null;

function viewReport(id){

    const report =
    reports.find(
        report => report.id === id
    );

    if(!report) return;

    currentReport = report;

    const content = `
--------------------------------------------------
                 Report Details
--------------------------------------------------

Report ID:          RPT-${report.id}
Report Type:        ${report.type}
Generated By:       ${report.generatedBy}
Date Generated:     ${report.dateGenerated}
Time Generated:     ${report.timeGenerated}

--------------------------------------------------
                 Report Summary
--------------------------------------------------

Total Students:     1,250
Cleared Students:   980
Pending Students:   220
Rejected Requests:  50

--------------------------------------------------
              Financial Information
--------------------------------------------------

Expected Dues:      ₦6,250,000
Paid Dues:          ₦5,100,000
Outstanding:        ₦1,150,000

--------------------------------------------------
Description:
This report provides an overview of student
clearance activities and faculty dues payments.

Status: Generated

--------------------------------------------------
`;

    reportDetailsContent.textContent = content;

    reportModal.classList.add("show");

}

/* =========================
   DELETE REPORT
========================= */

function deleteReport(id){

    const confirmed = confirm(
        "Are you sure you want to delete this report?"
    );

    if(!confirmed){
        return;
    }

    reports = reports.filter(
        report => report.id !== id
    );

    saveReports();

    renderReports();

    alert("Report deleted successfully.");

}
/* =========================
   DOWNLOAD REPORT
========================= */

downloadReportBtn.addEventListener(
"click",
() => {

    if(!currentReport) return;

    const content =
    reportDetailsContent.textContent;

    const blob =
    new Blob(
        [content],
        {type:"text/plain"}
    );

    const link =
    document.createElement("a");

    link.href =
    URL.createObjectURL(blob);

    link.download =
    currentReport.type
    .replaceAll(" ","_") +
    "_Report.txt";

    document.body.appendChild(link);

    link.click();
 
    URL.revokeObjectURL(link.href);
    document.body.removeChild(link);

}
);

/* =========================
   CLOSE MODAL
========================= */

closeReportModal.addEventListener(
"click",
() => {

    reportModal.classList.remove(
        "show"
    );

}
);

reportModal.addEventListener(
"click",
(e) => {

    if(e.target === reportModal){

        reportModal.classList.remove(
            "show"
        );

    }

}
);

/* =========================
   DOWNLOAD BUTTON IN TABLE
========================= */

function downloadReport(id){

    const report =
    reports.find(
        report => report.id === id
    );

    if(!report) return;

    const content = `
Report Name: ${report.name}
Report Type: ${report.type}
Generated By: ${report.generatedBy}
Date Generated: ${report.dateGenerated}
`;

    const blob =
    new Blob(
        [content],
        {type:"text/plain"}
    );

    const link =
    document.createElement("a");

    link.href =
    URL.createObjectURL(blob);

    link.download =
    report.type +
    "_Report.txt";

    link.click();

}

/* =========================
   RENDER REPORTS
========================= */

function renderReports(){
   reportsTableBody.innerHTML = hardCodedReportsHTML;
   console.log(hardCodedReportsHTML);
    if(reports.length === 0){
        return;
    }
  
        reports.forEach(report => {
        const badgeClass =
        report.format === "PDF"
        ? "pdf"
        : "excel";

        const row =
        document.createElement("tr");

        row.innerHTML = `

        <td>${report.name}</td>

        <td>${report.type}</td>

        <td>${report.dateGenerated}</td>

        <td>
            <span class="badge ${badgeClass}">
                ${report.format}
            </span>
        </td>

        <td>${report.generatedBy}</td>

        <td class="actions">

            <button
            onclick="viewReport(${report.id})">
                <i class="fas fa-eye"></i>
            </button>

            <button
            onclick="downloadReport(${report.id})">
                <i class="fas fa-download"></i>
            </button>

            <button
            onclick="deleteReport(${report.id})">
                <i class="fas fa-trash"></i>
            </button>

        </td>

        `;

        reportsTableBody.appendChild(row);

    });
}

/* =========================
   GENERATE BUTTON
========================= */

generateBtn.addEventListener(
"click",
generateReport
);

/* =========================
   INITIAL LOAD
========================= */

renderReports();
window.viewReport = viewReport;
window.downloadReport = downloadReport;
window.deleteReport = deleteReport;

/*====================================================
            DISPLAY ADMIN NAME
====================================================*/

const savedAdmin = JSON.parse(
    localStorage.getItem("adminProfile")
);
if (savedAdmin) {

    const adminName = document.getElementById("adminName");

    const dashboardAdminName =
        document.getElementById("dashboardAdminName");

    if (adminName) {
        adminName.textContent = savedAdmin.fullName;
    }

    if (dashboardAdminName) {
        dashboardAdminName.textContent = savedAdmin.fullName;
    }
}
/*====================================================
                    OPEN POPUPS
====================================================*/

function openViewPopup(reportName) {

    document.getElementById("viewReportName").textContent = reportName;

    document.getElementById("viewPopup").classList.add("active");

}


function openDownloadPopup(reportName) {

    document.getElementById("downloadReportName").textContent = reportName;

    document.getElementById("downloadPopup").classList.add("active");

}


function openDeletePopup(reportName) {

    document.getElementById("deleteReportName").textContent = reportName;

    document.getElementById("deletePopup").classList.add("active");

}


/*====================================================
                    CLOSE POPUP
====================================================*/

function closePopup(popupId) {

    document.getElementById(popupId).classList.remove("active");

}
/* =========================
   EXPOSE FUNCTIONS GLOBALLY
========================= */
window.viewReport = viewReport;
window.downloadReport = downloadReport;
window.deleteReport = deleteReport;
window.openViewPopup = openViewPopup;
window.openDownloadPopup = openDownloadPopup;
window.openDeletePopup = openDeletePopup;
window.closePopup = closePopup;
document.addEventListener("DOMContentLoaded", function () {

    const sidebar = document.querySelector(".sidebar");

    if (!sidebar) {
        return;
    }

    /* ================================
       CREATE MENU BUTTON
       ================================ */

    const menuButton = document.createElement("button");

    menuButton.className = "mobile-menu-button";
    menuButton.innerHTML = "☰";
    menuButton.setAttribute("aria-label", "Open menu");

    const topbar=
    document.querySelector("h2");
    if (topbar) {
        topbar.parentElement.prepend(menuButton);
    }


    /* ================================
       CREATE OVERLAY
       ================================ */

    const overlay = document.createElement("div");

    overlay.className = "sidebar-overlay";

    document.body.appendChild(overlay);


    /* ================================
       OPEN SIDEBAR
       ================================ */

    function openSidebar() {

        sidebar.classList.add("sidebar-open");
        overlay.classList.add("active");
        menuButton.style.display = "none";
    }


    /* ================================
       CLOSE SIDEBAR
       ================================ */

    function closeSidebar() {

        sidebar.classList.remove("sidebar-open");
        overlay.classList.remove("active");

        
        menuButton.style.display = "flex";
    }


    /* ================================
       MENU BUTTON
       ================================ */

    menuButton.addEventListener("click", function (event) {

        event.stopPropagation();

        if (sidebar.classList.contains("sidebar-open")) {
            closeSidebar();
        } else {
            openSidebar();
        }

    });

    /* ================================
       CLICK OUTSIDE SIDEBAR
       ================================ */

    overlay.addEventListener("click", function () {

        closeSidebar();

    });


    /* ================================
       SIDEBAR LINKS
       ================================ */

    const sidebarLinks = sidebar.querySelectorAll("a");

    sidebarLinks.forEach(function (link) {

        link.addEventListener("click", function () {

            if (window.innerWidth <= 768) {
                closeSidebar();
            }

        });

    });


    /* ================================
       ESC KEY
       ================================ */

    document.addEventListener("keydown", function (event) {

        if (event.key === "Escape") {
            closeSidebar();
        }

    });

});